# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: "Test Suite"

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.10"

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          python -m pip install tox tox-gh-actions

      - name: "Run tox for ${{ matrix.python-version }}"
        run: |
          python -m tox

      - name: "Upload coverage data"
        uses: actions/upload-artifact@v3
        with:
          name: covdata
          path: .coverage.*

  coverage_main:
    name: Coverage on main/dev
    needs: tests
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10"

      - name: "Install dependencies"
        run: |
          python -m pip install tox tox-gh-actions

      - name: "Download coverage data"
        uses: actions/download-artifact@v3
        with:
          name: covdata

      - name: "Combine"
        run: |
          python -m tox -e coverage
          export TOTAL=$(python -c "import json;print(json.load(open('ehr_coverage.json'))['totals']['percent_covered_display'])")
          echo "ehr_total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY

      - name: "Make badge: main - lib.ehr"
        uses: schneegans/dynamic-badges-action@v1.4.0
        if: github.ref == 'refs/heads/main'
        with:
          # GIST_TOKEN is a GitHub personal access token with scope "gist".
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 7c4939ecfd6b99a7b77dd1c4f789fd1b   # replace with your real Gist id.
          filename: covbadge_main_ehr.json
          label: "cov:lib.ehr"
          message: ${{ env.ehr_total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}
      - name: "Make badge: dev - lib.ehr"
        uses: schneegans/dynamic-badges-action@v1.4.0
        if: github.ref == 'refs/heads/dev'
        with:
          # GIST_TOKEN is a GitHub personal access token with scope "gist".
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: f15bea7fb1837fba360e742b10244429   # replace with your real Gist id.
          filename: covbadge_dev_ehr.json
          label: "cov:lib.ehr"
          message: ${{ env.ehr_total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}